# SleepingServerStarter settings
# true to enable, false to disable

# The name of your server.
# You can specify (https://motd.gg) by using the `ยง` prefix.
serverName: "Sleeping: Go to https://arnold.host to wake up..."

# The server name to display in Minecraft, defaults to serverName if not set
# serverMOTD: "SleepingServer, waiting for his prince... [MOTD]"

# Use Minecraft `server.properties` to overwrite 
# `serverPort`, `maxPlayers`, `serverOnlineMode`, `useWhitelistFile`, 
# and `useBlacklistFiles` properties
#useNativeFiles: false

# The port of your Java Edition server (0 to disable)
serverPort: 25565

# The port of your Bedrock Edition server (0 to disable or add `#`) 
bedrockPort: 19132

# Message shown when the server is off and someone is trying to connect
loginMessage: "...Waking server up, come back in a minute..."

# Like in the server.properties, to check the licence of player or not.
serverOnlineMode: true

# Use legacy "login" method
# https://github.com/PrismarineJS/node-minecraft-protocol/issues/1279#issuecomment-1878866611
# Enable legacy login to fix protocol decoding issues with newer Minecraft versions
useLegacyLogin: true

# Maximum amount of players
maxPlayers: 20

# Web page port
webPort: 5000

# Stop the web-server when minecraft starts 
webStopOnStart: false

# You can specify an absolute path to serve instead or an url to redirect to.
# true or false to enable, by default it will serve ./plugins/dynmap/web/
# https://github.com/vincss/mcsleepingserverstarter/wiki/Use-internal-SSS-WebServer-for-dynmap
#webServeDynmap: false

# Add a button in the web-ui to restart the minecraft server proxy
#webAllowRestart: false

# Start the Minecraft Server
startMinecraft: true

# Server start command
# paper.jar or whatever flavor you like
minecraftCommand: "/home/pi/minecraft/jre/bin/java -DPaper.IgnoreJavaVersion=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar -Xms400M -Xmx6500M /home/pi/minecraft/paperclip.jar" # or paper.jar or whatever flavor you like

# Set a custom Working Directory for the server (path to minecraft server folder)
# Edit this setting only if you know what you are doing!
# If you don't know what, don't to edit it.
#minecraftWorkingDirectory: ""

# Automatically start the real server instead of the sleeping one
#minecraftAutostart: false

# Customise the delay between when the minecraft server stops 
# and the sleeping server restarts (to ensure conection are closed)
# in milliseconds
restartDelay: 5000

# Prevent the user to stop the server (trought web-server or cli).
preventStop: true

# Discord WebHook
# https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
# Setup a Discord WebHook to your channel
# discordWebhookUrl: "https://discord.com/api/webhooks/REPLACE_ME"
# Avatar of the bot in the Discord WebHook
# discordWebhookName: "SleepingServerStarter"
# Avatar of the bot in the Discord WebHook
# discordWebhookAvatar: "https://raw.githubusercontent.com/vincss/mcsleepingserverstarter/master/docs/sleepingserver.png"

# Only allow these player name on the white list to wake the server up
# example ["vincss"]
#whiteListedNames: [""]

# Use Minecraft `whitelist.json` instead of the `whiteListedNames` property.
# Checks both username and UUID
# Disabled for sleeping server - allow anyone to wake the server
# The actual Minecraft server will enforce whitelist via EasyWhitelist plugin
useWhitelistFile: false

# Prevent connections from those addresses to wake up the server
# example ["149.102.143.151", "132.145.71.44", "45.128.232.206", "193.35.18."]
#blackListedAddress: [""]

# Use Minecraft `banned-ips.json` and `banned-players.json` to prevent players from waking up the server.
# Can be used together with `blackListedAddress` property
useBlacklistFiles: true

# Use a custom icon 64x64 png 
# converted using https://www.base64-image.de
favIcon: data:image/webp;base64,UklGRrYHAABXRUJQVlA4TKkHAAAvv0AoELfAprb2Juk92dqegy0mFKALBRxmLDD2JqBKYRoAYJI035pWP2uJA/iMrpkLqG4HQGcb2baS754pFTC0Q0459EBBFnoFEGloqYCgyP/RItnksuSud5Vdpp86RU5dz80JgwBEEiVZixOursuapvr/f+ux89LpxlpVFcZlM8y9tl3c3yPhuJEkRVLm0Ujpv8UDx/+I/k8A/31M9QKl4pW6qqmNwEkdqKBW9By0XzWNMdpzwhhuAGp6qFd1Y5vhuqKS1byClrADHqoF03mb530Z1KuOQdG23baVA1Jy0fT//8mUKVEzsdYzTVxcQkpPIkKiJNlx28A5uly09QDieIBY+oAPcvpf//tf/goqSXkBiugZ6Xmd8gJ8w/nopTk4Ab7gXNRsDn+ATZyHWM2RkEDKGQgLpNACfIZ4QqqbgxRgjZNRqzkIAbZwIgKbY5SHN8Is+wHL9e37GwfjMwIfcvVz+wElHpiNgsIObD+aQuAlqBaOJDLwPwOwYj0OUfQG/HXih3ygqYruCEXkZglDSyIfiDoK5LE0heNF1CuOBbmZQloi4UrZn6kd5OUG725oKa4OAcCObD/Gyw2e3dDiG5Ag7Mj2I5Q3ALshl15idMCeMvf4pQKwG6rVCdWSFRd4RxutstrjbYL/KDIBInlbiV0grG9VJUpceIk/It5jwYwNiVtIsw8eBcV7FERBQHUw7EDlPhEySoUT4AcyF+khLjDKB5GLcJCA/B5cCw6GOtX1A8zvH+BafDS0H0Jk4wHmQpHhEA/sZplvASfx70BZ5AbIh1nuNImEKO9MTILBkA8z4QojwIBFZDJQ2tic+5JjSvJbJ/OgtC/Y/InPckQ9r8MgvwHL8yyD3VEVHJBHkwNfod3tYA8zPbQ67c8He5rTk9DMrNAAJCsHVDWmRqPuSsXYLGZ67BuZW7Tzj30HFug7L6ceKTLr9NI54sG8N3ek3GXG4FG2RyauHAEyKnKOTANJdfPGEnJq58PkQcEbY7BCmiWHkGt8eDA1L/iNUXIrgNKe63IIucY3jsnOib2lZCSsGWumIdaGI4F3YpXr5M/qi78Xlxm7zUPU9zvvq40sXhT3GPzR6qYxBXTVKzqORnhvSJTE1DzzMNoXfLCrcKXp8fzuATEiO/E2ZuGp6qkHQEFCEQ9mwf7SpEFRaHBky1xFQCFBIBBVHriGEL25YADWobXnDsF7RVgIAMJdzmQdC9b+PIVQd6SE5BhEJGISXmizhbLfikjoHMhD4iXhPL30EbKmTgBDvhNPHNTblIV7xUSFHfi9kxwdgQvN4oWAALLkILor0IzK6PluiAepfTiPS4kCIzYBxdYPyeogTI0sMTOaYqzovbKPNaTiYw+jqyQ7uq0u1EM2P1TB006HiiSeqjFsR7d1EOECBU/aUGEjdcTVxmi219Yv9eKBJ8HVhtW0W308Gxth9PJGvBnH1yFi+qvFW3bJLF0Iqg5GYsIniaM4BzsZA1Opp0K/JVdKbP00Sr9yuxHPSLpJn9t4AG1VdzkYtIDoI7wvXdoKCcUg9y5yAJdG+TUw6PLhW1fZdco8ZEidZqRZdvg4MDZgdcD87P8dpZJY0NVdRlH2ytzeH/d9Q4uHtQk8M2cDFu1+e5ESBq6U0I8Lrg5Q6Yqx26yFqw808TDZwQ1gZr4g1awHeazOr2gjeXv01EbC9xU3E0qYHHvlXARkF8BAb40f3dAbRJTGQHIgJZe0fr4ZrH8KJ/9NySCwEK/tOtegzCDEeSdWLgBLJdV1bmCNLVUebv5ygQ+/rlv0K5S4s+LoYj/XH0zNyi3eSBcyrmpv47boErm5sTBxledgs7fRW2gB0IUHfK5LenE/t7D7M7FMkeM2LhxAr9u6Y5tRq68yWKonRa/4f4rI2hwgNwgs2dX6KgJIalB1BWHnzetr+fKQlb0a7TLao+WCydqpcQWilfU3sL2pbkX2WrojufYs9l97rTMxKC4H7D3Lun1stSL/gZBMeigcv2AQVL5ylw3qOl3h1LsfGJxSr0TEh42xkQWDnuG15J2AcF2RRJ2C0QgnTT2ASwTHgP+eGo53Sl1ohDJ1wAqv4zgc482Fu72uZHMIGbH+9oyUdwEk+LkiR+x35JERJxbz1aqwTdyROQsv0GwMIrlapA2F0dYLrJDVHXzincCgSM77WdryYDFe7aXBedC+50ePBE8HbSh7f61AIN5mUvVpcLfq5n/84sE+IVAwEC88f/yyJ9zpOdyAf5hQIJAIBxHORjW2ttPrcDO+zYSCgYSC2l2ijal9u4Efi/mhGtpVQLpOeFI6IrTDPhpHsQ/8Nns+05AovU8BBjv+salq+rJ0ZKjCF9uxj+ZEmFo6Mpzrkh33aC5EKaLSW1MAyNptikx2FOFfLSHHG4tkvHMqZ9GzIogN4w26xrnDbYYbKSutNq06BYeZkbWP9yDkTK1RXafwSPZSlwWBT1f3bv0ItOqJwikXTIWFWcciEBxyo6nYyO4MCRcFlQ5RDFwJOp1PMLdx9R6Nns7nr6M4VcG/fU2YzuuvIJ/bkxdMZ4WXz02y+8Fi63zQVgW7Fy9tnRNe1UZu94flfMQ+23r9xN7zxGze5lrnh7bkCUPnibk9zTV0npjtZSayBAA=
# Path to a PNG file to use as the server icon.
# If this is set to server-icon.png then it will use the same icon as the server.
# favIconPath: sss.ico

# Force compatibility with a specific minecraft version.
# If set to false, it should handle any compatible version.
# version: false

# Hide the ip from the remote player in the logs
#hideIpInLogs: true

# Hide pinging logs
#hideOnConnectionLogs: true

